### ISSUE TITLE
Address space

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#120]
More than one person has mentioned to me in the last couple of days about the use of `fd00::/8` address space, as this is active space for private allocations, and results in direct collisions. 

I think I agree that `fd00::/8` is not really a good candidate - even my own network has overlap as a result of this.

Some suggestions have come in the form of:

- Using `fc00::/8` and accept that conflicts with cjdns will arise - is it actually in the scope of our project to deliberately avoid collisions with cjdns?
- Squat in `4000::/3` as this is space that is soft-assigned to the ITU for regional allocation, and apparently the Internet Architecture Board think this is never going to happen because their plan is insane
- Squat in `0200::/7` as this is deprecated since 2004 pending a change to the NSAP-IPv6-whatever RFC that nobody has apparently been bothered enough to update in the last 14 years

**Comment by Arceliar** [comment]
The main reason to avoid `fc00::/8` was indeed to avoid conflicts with cjdns, since most of the people I know who are interested in this sort of thing are already running cjdns.

Squatting somewhere outside of `fc00::/7` isn't ideal, but I guess I'm OK with it if we can't find a good alternative and `fd00::/8` is causing problems for people, and if we want to continue not conflicting with cjdns. Note that the current code assumes the prefix is a multiple of 8 bits, so we will either want to pick a `/8` or revisit that if we make a change. Another range to consider may be the deprecated site-local `fec0::/10` range, but some platforms may still have legacy code that handles that range specially.

If we keep using `fd::/8`,  then nodes should ignore yggdrasil when trying to send to nodes in a prefix longer than a `/8`, so I think it would only be a problem for people who already use `fd00::/8` in a way not covered by [rfc4193](https://tools.ietf.org/html/rfc4193), which specifies 48 bit prefixes or longer.

**Comment by neilalexander** [comment]
Indeed - the question is whether we accept the collision with cjdns and expect users to run one or the other, use network namespaces, etc, or if we make an active choice to avoid it. 

`fc00::/8` I suppose is the only range that is guaranteed to remain local. 

The site-local range might be fine given that the operating system will never see the routing behaviour and will only send packets onto the interface. 

Otherwise we could use one of the allocated ranges but that feels messy.

**Comment by Arceliar** [comment]
Fixed in `develop`, we're switching to `200::/7` (which has a nice symmetry with the `2000::/3` range that globally routeable IPv6 currently uses). Nodes will need to update for it to work, but the change is transparent for intermediate nodes when they route traffic or respond to lookups. This will unfortunately mean that nodes hosting services of any kind will need to update their configuration and/or DNS records to point to the new addresses.
