### ISSUE TITLE
Explore UNIX domain sockets for admin

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#153]
Right now the admin socket listens on `localhost:9001` by default. This can also be changed in config.

It would be worth checking if UNIX domain sockets are a more sane option on some platforms.

**Comment by Arceliar** [comment]
Hypothetically, I think we could change the `AdminListen` line to use the URL-like `tcp://localhost:9001` syntax (falling back to `tcp` if nothing is specified?). We could then pass the protocol type as the `network` field to `net.Listen` and `net.Dial`, so we'd get this functionality almost for free.

For that matter, we could consider adding support for unix sockets to `Listen` and `Peers` in the config, though I'm not sure there's a use case for a ygg instance that listens only over unix domain sockets...

**Comment by neilalexander** [comment]
#154 provides a solution for the admin socket. Do we want to add support in `tcp.go`

**Comment by Arceliar** [comment]
Adding support in tcp.go would mean we *probably* need to add support for multiple listeners, so we can listen on unix sockets and tcp at the same time. Otherwise we run into the scenario where we can have two networks, one of which only communicates over unix sockets, the other only communicates over tcp, and there's no way to link them.

We can/should add support at some point, if only because it's such low hanging fruit, but I don't think it needs to be a high priority right now (and we may want to do a little refactoring at the same time -- rename `tcp.go` to `link.go` or something like that, and then move any tcp-specific parts into a `tcp.go`). This would likely also break configs, since we'd probably need to convert the type of `Listen` from `string` to `[]string`, so that may need to wait for v0.3 or something.

**Comment by neilalexander** [comment]
Multiple listeners is a good idea - especially if we want to mix and match protocols. I agree that we can solve the UNIX socket support at the same time.

**Comment by Mikaela** [comment]
> I'm not sure there's a use case for a ygg instance that listens only over unix domain sockets...

Yes, [Tor hidden services support unix sockets](https://torproject.org/docs/tor-onion-service.html.en) and there are [public onion peers](https://github.com/yggdrasil-network/public-peers/blob/master/other/tor.md) :smile:

**Comment by neilalexander** [comment]
Completed by #238.
