### ISSUE TITLE
Package refactoring

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#241]
Separate some of the TUN/TAP and IP logic out of `src/yggdrasil` so that we can reuse it as a library.

Perhaps move it into `src/yggdrasilnode` so that `yggdrasil.go` can still be a simple wrapper that does nothing but feed in config.

**Comment by Arceliar** [comment]
So, `crypto.go` has no outside dependencies, meaning we could easily move that into a separate package and export the useful parts. The only dependency of `address.go` should be `crypto.go` (for the `NodeID` stuff), so that can also be moved into a separate package. This would let users more easily write their own tools to do things like convert keys to IDs/addresses, parse addresses into IDs and bitmasks, etc.

**Comment by neilalexander** [comment]
I think this has just about been covered by #419.
