### ISSUE TITLE
Advertise IPv6 capabilities on macOS

### ISSUE THREAD

**Issue by yangm97** [yggdrasil-network/yggdrasil-go#307]
So that safari and other applications will allow using yggdrasil-based dns addresses even when the underlying connection is IPv4 only.

https://apple.stackexchange.com/a/345540

**Comment by neilalexander** [comment]
So it's neat that there's a solution for this - it's annoying that macOS wilfully ignores IPv6 on the `utun` adapters, but I'm not entirely sure how we should handle setting this config.

Given that the `utun` interface number isn't known before Yggdrasil starts (and we have no way to manually select it), that rules out using wrapper scripts in the macOS package. Writing this kind of config *inside Yggdrasil* would probably work, but we should also make certain that we undo any configuration when Yggdrasil shuts down.

The problem would be what happens if Yggdrasil crashes and leaves behind some config - if we have a good strategy for cleaning that up or checking the config before rewriting it at the next start.

**Comment by yangm97** [comment]
It seems that, at least when you set it manually, it won't survive a reboot, so worst case scenario we got that for us.

**Comment by neilalexander** [comment]
That's good to know - does it persist across Yggdrasil restarts too? Curious if it disappears when the `utun` disappears.

**Comment by yangm97** [comment]
Seems like the setting persists. 

But by the looks of it, I'm creating a service manually with that commands, so I'd expect some polishment from using the api directly. You mentioned you got ygg to work as a vpn service on the matrix room, maybe macOS does the job of cleaning up settings if you use that API?

**Comment by neilalexander** [comment]
For what it's worth, the iOS code actually can be reused on macOS to create a true-to-life Yggdrasil VPN provider that appears in System Preferences, supporting connect-on-demand and everything.

It's quite likely I will look to start packing Yggdrasil for Mac up in a wrapper like this before too long, so that it is easier to install and manage.
