### ISSUE TITLE
iOS app add VPN as personal

### ISSUE THREAD

**Issue by iShift** [yggdrasil-network/yggdrasil-go#341]
In iOS we have 2 types of VPN: 
1. Global
2. Personal

Now Yggdrasil add vpn as global, so you can’t use vpn in vpn (you need that if you use DNS Over HTTPS from Cloudflare 1.1.1.1 or other VPN) 

It would be cool, if Yggdrasil can add there vpn as personal, such as TunnelBear do...

![aba7e85d-9f19-41ed-8faf-7284a8b07eed](https://user-images.githubusercontent.com/426427/53467988-6b702700-3a69-11e9-84af-b3b89d52b01c.jpeg)

**Comment by neilalexander** [comment]
Sadly I don't think this is possible - the only reason TunnelBear comes up as a "Personal VPN" is because it is IPsec/IKEv2, which is a built-in VPN provider in iOS set up through a configuration profile. Packet tunnel extensions which implement custom protocols, like Yggdrasil, are under the "Global VPN" category.

**Comment by iShift** [comment]
I’m not shure about reason IPSEC, this VPN use IPSEC but it in global

**Comment by neilalexander** [comment]
That's because IPsec VPNs can be configured in a variety of ways, including using `NEVPNManager`, configuration profiles, MDM etc. 

Yggdrasil doesn't use IPsec or IKEv2, hence the reason I believe it to be confined to global.
