### ISSUE TITLE
UDP transport

### ISSUE THREAD

**Issue by jcgruenhage** [yggdrasil-network/yggdrasil-go#345]

**Comment by neilalexander** [comment]
So we did have a UDP transport in the past and it was eventually removed due to some problems with the chunking. Since then the code has been refactored quite a bit so that the protocol semantics are handled differently, therefore new chunking code for UDP has the potential to be much cleaner than it did before.

I am mostly unsure whether there might be some problems with the re-ordering of packets here, as I think we are quite sensitive to that in some areas to prevent loops. We can either make attempts to guarantee packet ordering, at which point we're almost reinventing TCP, or we may have to investigate the areas of Yggdrasil which are sensitive to ordering.

**Comment by Arceliar** [comment]
So order-wise, the main issue is that it's if A sends a switch message (spanning tree stuff) to B, and then forwards a packet to B, it's not safe for B to do anything with that packet until the switch message has been handled, otherwise routing loops can happen. We currently don't need to worry about that because of TCP stream semantics.

For UDP, we *could* just implement stream semantics with reliable ordered transmission, and that would solve the problems (using quic would also count, I suppose), but then we're just pretending to be TCP (and probably doing a bad job of it). But it's more interesting to consider cases where we don't try to follow stream semantics exactly.

So what we could think about is something that's:
1. Reliable (possibly with congestion control of some kind?), even in cases where it needs to chunk packets somehow to avoid fragmentation.
2. Unordered.
3. But stamps traffic with some sequence number or something, to indicate if any (important) protocol traffic has been sent, so we know when it's *not* safe to handle things unordered.

Then we could process packets without head-of-line blocking, except in cases where certain protocol traffic is dropped (in which case we'd need to buffer or drop any out-of-order packets until we get the rest of the protocol traffic). I'm not sure how much of an improvement that really is compared to what we currently get from TCP. Worth thinking about / investigating further.

**Comment by akhilman** [comment]
Please do not control the underlying UDP packet stream, let applications control the order and integrity of the packets for them self. In the case of audio / video transmission or VoIP, an attempt to resend the packet will lead to a much worse result than its loss.
Wrapping everything into QUIC will not solve this issue.

**Comment by cathugger** [comment]
>  Wrapping everything into QUIC will not solve this issue.

https://tools.ietf.org/id/draft-ietf-quic-datagram-01.html if this is used it probably would.
Not to disagree with what you're saying, though.

**Comment by neilalexander** [comment]
It's worth noting that there are a number of additional considerations in v0.4 with regards to preventing races in path setups/teardowns etc which are not covered in the earlier (and probably out-of-date) posts in this issue. Traffic packets don't really need strict ordering but we do need to think about how to guarantee correct ordering for some protocol traffic.

In any case, we know that it's a problem we have to solve. It's just that there are more important things for us to work out first.

**Comment by OlegGirko** [comment]
> It's worth noting that there are a number of additional considerations in v0.4 with regards to preventing races in path setups/teardowns etc which are not covered in the earlier (and probably out-of-date) posts in this issue.

Is there more current information available?

> Traffic packets don't really need strict ordering but we do need to think about how to guarantee correct ordering for some protocol traffic.

TCP does not solve reliable delivery as well. There will be lost messages when TCP connection is closed for some reason, and there is no way for a sender to know what was actually received on the other side. Hence, reliable state synchronisation protocol is needed anyway, and if it's designed properly, TCP has surprisingly small advantage over unreliable datagram transport for this.

Using analogy from instant messengers, this is how XMPP does it wrong (sending messages and relying on TCP) and how Matrix does it right (synchronising state). Yes, Matrix is much more complex, but there is no correctness without this complexity. And due to its basis on reliable synchronisation, Matrix is surprisingly easy to adapt to use datagram transport (CBOR over CoAP instead of JSON over HTTPS).

Ordering issues are just a very small problem here and it's easy to solve. There are multiple approaches, like generation numbers or other ways of data chaining.

Even if TCP-like properties are required for routing protocol to operate, then requiring TCP-like properties from underlying medium is harmful for data packets, and re-implementing something TCP-like just for routing protocol will be a waste of resources and over-engineering. But there is already functional TCP that can be used for that. It's just located on top of the tunnel level, not below it. Yes, TCP on top of Yggdrasil can be used for routing updates, in the same manner as BGP uses TCP over IP. Routing updates are exchanges between adjacent nodes anyway, and their reachability is not dependent on routing updates, so there is no way chop off the branch on which you sit even if you rely on TCP over functional tunnel to update routing inside this tunnel.

> In any case, we know that it's a problem we have to solve. It's just that there are more important things for us to work out first.

What are these more important things?

**Comment by neilalexander** [comment]
@OlegGirko 

> Is there more current information available?

The recent changes aren’t really documented at any great length yet. There’s a little bit of information on the blog: https://yggdrasil-network.github.io/2021/06/26/v0-4-prerelease-benchmarks.html

> TCP does not solve reliable delivery as well. There will be lost messages when TCP connection is closed for some reason, and there is no way for a sender to know what was actually received on the other side.

At the moment this is acceptable for us. If the TCP connection fails then traffic can get dropped and the peering dies and that’s OK. We learn quite quickly that the peering has died and we can even detect the pressure on a link building up before that.

Traffic can get dropped for other reasons too (like exceeding the buffer size within the switch for a given port). TCP over Ygg will deal with that case. UDP over Ygg won’t, but then it’s an application-level concern to deal with packet loss.

> Ordering issues are just a very small problem here and it's easy to solve. There are multiple approaches, like generation numbers or other ways of data chaining.

Indeed, and eventually we’ll get to it. :-)

> Even if TCP-like properties are required for routing protocol to operate, then requiring TCP-like properties from underlying medium is harmful for data packets

It’s not *quite* that black and white, but I see what you’re getting at. Using TCP is arguably what allows us to quite smoothly support giant MTUs, which allow us to a) carry much larger packets than normal which largely corrects for TCP-over-TCP amplification and b) reduce the number of syscalls for the same amount of data which reduces context switches. UDP might gain some unexpected reliability within the scope of a specific peering, sure, but not really anywhere else, as traffic can be dropped for other reasons as mentioned before.

> What are these more important things?

Ultimately engineering and testing a routing protocol that will function at scale, which is the #1 goal of the project. It’s more important for us to get that right first because without it the project won’t succeed anyway. Ultimately the rest — how peerings work, how traffic is prioritised/queued/transported/dropped — is nothing more than implementation detail.

**Comment by neilalexander** [comment]
v0.5 will have QUIC support.
