### ISSUE TITLE
Announce peers via nodeinfo

### ISSUE THREAD

**Issue by jcgruenhage** [yggdrasil-network/yggdrasil-go#347]
People want to see a more complete map of the network, but that isn't possible today. A config switch that puts all current peers into nodeinfo would help here.

Due to privacy concerns, this should default to false though, to not leak too much data.

**Comment by neilalexander** [comment]
If anything my concern with this is that if node X has peers A, B and C, and then node X chooses not to volunteer peering info for their privacy but A, B and C do, that this still compromises the privacy of X. 

Given that Yggdrasil doesn't require this information to operate, and it would be purely informational for the sake of drawing maps, I am not sure if this is a tradeoff we should accept.

cc @Arceliar.

**Comment by jcgruenhage** [comment]
Good point on involuntary information leaks! This could sort of be circumvented with more nodeinfo entries, like "please do not leak peering information about me". Still, not sure whether it's a good idea, but I've seen a bunch of requests about maps that show more links in places like reddit.

**Comment by Arceliar** [comment]
Hypothetically, if we wanted to get a remote node's peers, I would probably prefer to add a *temporary* remote version of `getPeers` as a debugging tool, or add it to the nodeinfo, which would probably be dropped before v1.0.0, just so we can use it to implement something like traceroute (and I guess the map could use it too, but that's *also* misleading, since things won't necessarily follow the shortest path--we'd need to update the map to show the tree path and all greedy paths that are at most the same length, if we wanted to give a real picture of what it does). Given that parent/child relationships are already leaked, I'm not sure how  much more it hurts privacy to add that. But I'd rather avoid that until we run into a problem that really requires a traceroute to debug, just to err on the side of privacy.

**Comment by neilalexander** [comment]
We have a temporary version of remote_getpeers in v0.4, which allows crawling the network while we're alpha-ish. It'll get removed eventually but I think for now we can close this issue.
