### ISSUE TITLE
yggdrasilctl getPeers show down peers

### ISSUE THREAD

**Issue by passenger245** [yggdrasil-network/yggdrasil-go#392]
unreachable peers seem to be invisible. request for feature to show all peers

**Comment by neilalexander** [comment]
I am not sure that there's a way we can do this reliably, because the `endpoint` peer attribute won't match the `Peers`/`InterfacePeers` entry if there is DNS involved, nor would it match if the connection was incoming instead of outgoing. 

When we add public key pinning, this might be easier, as then we can just list the peer entries for public keys we aren't connected to.

**Comment by neilalexander** [comment]
Configured-but-down peerings are now shown in `getPeers` in v0.5.
