### ISSUE TITLE
Logging to file

### ISSUE THREAD

**Issue by Vort** [yggdrasil-network/yggdrasil-go#396]
When yggdrasil-go is launched as Windows service, logs starts flowing to nowhere.
It would be good to have an option in config file, which will redirect (or copy) all log output to specified file.

**Comment by neilalexander** [comment]
This is an interesting one. With very minimal effort we can write out the standard logging from Yggdrasil to a file, but what we can't do (as far as I'm aware) is to capture all of the panics and redirect those too. Redirecting stdout is a particular challenge with Windows - as far as I know that can't be done in the usual ways.

**Comment by Arceliar** [comment]
Mentioning it here so it doesn't vanish in the matrix/irc scrollback.

While we can't redirect `panic` messages to the logger, it looks like we *can* [redirect `stdout`/`stderr` to a file](https://stackoverflow.com/questions/34772012/capturing-panic-in-golang) after startup, it's just an ugly thing to do. It sounds like `panic` actually uses `stderr` rather than `stdout`, which makes sense I guess.

I'm not actually sure if that *redirects* the output, or if it sends a copy of the stream to the file while still printing. I'm not sure it matters for our use case.

**Comment by neilalexander** [comment]
This has now been implemented into `develop`.
