### ISSUE TITLE
Encryption *and* Signing keys?

### ISSUE THREAD

**Issue by kousu** [yggdrasil-network/yggdrasil-go#397]
When this protocol gets deployed widely, I think having to distribute *two* keys per node is going to get complicated, fast.  GPG has demonstrated that having multiple subkeys that need to be manually managed by humans is asking for confusion and misencryptions. Like TLS and Signal, WireGuard [manages](https://www.wireguard.com/protocol/#data-keys-derivation) to use a single signing key to bootstrap the whole protocol; the trick is to use *[ephemeral DH](https://en.wikipedia.org/wiki/Elliptic-curve_Diffie%E2%80%93Hellman) keys* that only last as long as a "session" (a short time, a [few minutes](https://www.wireguard.com/protocol/#connection-less-protocol)). The ephemeral halfkeys are signed by the static signing keys, but are themselves not secret because they don't have to be.

I see you're [using ephemeral keys already](https://github.com/yggdrasil-network/yggdrasil-go/blob/master/doc/Whitepaper.md#cryptography) so why do you need a separate, static, encryption key?

I'm **super** excited for Yggdrasil (and cjdns). I want to help get it right from the start.

**Comment by neilalexander** [comment]
The thing to understand here is that in Yggdrasil, encryption keys and signing keys have *very* different purposes.

Encryption keys are used in the *router* to derive the node ID (and therefore, by extension, the IPv6 address/subnet) and to ensure that we can encrypt traffic over the wire.

Signing keys are used in the *switch* to aid nodes in determining their path to the root in an authenticated fashion and to enable nodes to determine how the spanning tree orients itself.

These two functions take place independently, hence the two pairs of keys. We don't actually use the signing keys to authenticate the messages at the router layer at all.

**Comment by kousu** [comment]
Thanks for the quick reply and the explanation! I figured this would get tagged that way, and I'm glad to raise philosophical points.

I've read the whitepaper and I can't make sense of this point. Would it make more sense to call them "identity" and "routing" keys? Or "identity" and "tree" keys? But why couldn't you use the same key for both functions? They're both ed25119 keys?

I just read the comments closer:

```
  # Your public encryption key. Your peers may ask you for this to put
  # into their AllowedEncryptionPublicKeys configuration.
  EncryptionPublicKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

```
  # Your public signing key. You should not ordinarily need to share
  # this with anyone.
  SigningPublicKey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
```

so the signing key is public but potentially ephemeral. In that case, why expose it to the user at all?

My main concern was that you required key distribution of two keys at once. I think they could use more obvious names, but now that I understand you don't I'm okay with this. Thanks!

**Comment by neilalexander** [comment]
We could potentially call them "identity" and "switch" keys or something similar to that in the future - that might be a bit clearer. I would defer to @Arceliar on his opinion there.

The signing keys are Ed25519 keys but the encryption keys are Curve25519 keys.

Either key *can* be generated at startup – if the encryption key is randomised then your IPv6 will change on each startup, and if the signing key is randomised then this will potentially affect how the switch converges.

However it's often easier to stick with static keys in most cases because then we aren't masking bugs or other undesirable behavior with additional layers of randomness, especially during the project alpha stages.

**Comment by Arceliar** [comment]
I am OK with renaming them in principle, but that's one of those things we should do on a major release (0.4.0 I guess), when people are (hopefully) more likely to review their config files anyway.

Having the two different sets of keys is also important for anycast setups, if/when we add specific support for that. Signing/switch keys need to be different, otherwise the nodes with duplicate keys can appear to be a looping route and won't be usable by the network, but crypto/identity keys need to be the same (to make sure they get the same IP address, for anycast to work).
