### ISSUE TITLE
Use precomputed lookup table in switch

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#41]
Created in response to two `TODO`s in `switch.go`. 

> Instead of checking distance for every destination every time, maintain an array of structs, indexed by the first coordinate that differs from our own. Each struct has stored the best port to forward to, and a next coord map. Move to struct, then iterate over coord maps until you hit a dead end. The last port before the dead end should be the closest.

**Comment by Arceliar** [comment]
I have a working version of this somewhere in the python scripts. The catch is, a pre-computed table becomes invalid if anything related to route selection changes. That's fine if *only* coords are used, but it becomes a problem if estimated bandwidth is involved, since the estimate can change very frequently. The same issue would apply if latency was used instead.

So an option would be, instead of storing the single best port, store all ports that lead to a node that's closer to the required part of keyspace than ourself. That reduces the number of nodes we need to compare against when doing distance calculations. The bandwidth estimate part is already stored elsewhere, so this table would only need to be updated when someone's coords change (ideally, we'd only update the part of the table affected by the coord change, but for a first pass it should be enough to clear the table and recompute the whole thing).

**Comment by Arceliar** [comment]
This may turn out to be mutually exclusive with backpressure routing, depending on how things go. All else being equal, I think it would be preferable to use backpressure and ignore the pre-computed table approach (lookups profile as a negligible fraction of CPU time currently).

**Comment by Arceliar** [comment]
Incompatible with the new(ish) way the switch queues work, so closing.
