### ISSUE TITLE
Wire protocol changes

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#42]
Created in response to a `TODO` in `wire.go`.

Currently the wire protocol is sensitive to order, which means that most changes to the wire protocol would be breaking changes.

Some possibilities here:

1. Using something like protobuf instead
1. Adding field IDs and length values to allow reordering

**Comment by Arceliar** [comment]
At a minimum, it probably makes sense to add some kind of version number to the UDP and TCP peer links, which would be updated each time any breaking wire format change occurs. Then we could at least identify peers with an incompatible version, and disconnect from them. Fixing version incompatibility is a little less important than detecting it, in my opinion.

**Comment by Arceliar** [comment]
Just to document things a little better:

In the current wire format, fixed size arrays are trivial to use if you know the size. Slices are length prefixed. The uint64 wire format is a slice with no length prefix, but using an approach along the lines of [VLQ](https://en.wikipedia.org/wiki/Variable-length_quantity) (where the least significant bit is used as a sign bit for int64, and the rest is the absolute value of the number, where `-0` should correspond to all 1 bits--though I guess I should test that at some point).

The wire versions of packets are then marshaled/unmarshaled with hand-written `encode` and `decode` functions. We could probably replace all that with a reflection-based encoder and decoder. The key thing is that each wire encoded struct begins with an encoded wire type number, which is used to identify what kind of struct it should be decoded into.

If we switch to another format, there's a few things to consider:

1. We want the overhead to be small. Self describing formats sound nice, but that overhead can really add up when we only have a few packet types to worry about.
2. For performance reasons, we want to be able to route a packet without needing to unmarshal it into a struct, to avoid any unnecessary allocations. The current format allows for this. Many alternatives do not.

**Comment by Arceliar** [comment]
The more I think about this, the more I'm inclined to think that keeping compatibility within an existing wire packet type, while nice in theory, may be a bad idea in the long run.

The better option, I think, is to introduce a new wire packet type for any packets where an incompatible format change happens. We would keep around (but stop using) the old packet types after incompatible changes are made. We could keep around the handlers for slightly old packet types for a little while, if we want compatibility across changes. This is perhaps slightly more work to do in the code, but it keeps the wire formats free from any unnecessary overhead. So for example, if we add a new field (in an incompatible way) to `wire_DHTLookupResponse`, then we would need to introduce a `wire_DHTLookupResponse_v2` for the new packet. We would eventually remove the handlers for the old (unnumbered, but really v1) packet types.

Shortly before a 1.0 release, we would possibly want to clean up any old packet types, so they start numbering from 0 with no gaps again, since 1.0 is (presumably) stable and free from future wire protocol changes for the foreseeable future. That could be accomplished by temporarily cloning all the existing packet types into larger numbered ones, then swapping to use the large numbered ones, then removing the low numbered ones, then adding new clones (sensibly ordered, with no gaps) back at the start, switching to use the new clones instead, and then finally removing the high numbered clones. That's extremely tedious, but doable, and I'd rather pay that cost once near the end of beta (if things make it that far) than be slowed down by versioning and compatibility this early. In the `wire_DHTLookupResponse` example, it means we would create a new `wire_DHTLookupResponse_vX` equivalent to the last good format, then remove the old one after the switch, create new packets with just `wire_DHTLookupResponse` (no version specified) along with other packet types (starting the numbering over at 0), and then migrate to the new/final ones.

The main area that still needs work is the part outside of `wire.go`, namely `udp.go` and `tcp.go`. These need more thought, but the main thing they both need to do is exchange keys, read packets off the wire, and write packets to the wire. The reading/writing parts are inherently at last somewhat different (datagram based vs stream based), but the key exchange part could probably reuse the same structs and encoding/decoding code for both socket types. We *could* promote key packets to be in `wire.go`, but then disconnect packets should also be there for symmetry reasons, and those are only needed in UDP, so I'm not sure it makes sense to have them live anywhere other than `udp.go` for now. In which case, I prefer to keep the key and disconnect packets for UDP in `udp.go` for now, just as the gory details of working with datagrams over a stream are hidden in `tcp.go`. These can be moved to something like `datagram.go` and `stream.go` later, if other datagram-oriented or stream-oriented protocols are supported.

**Comment by Arceliar** [comment]
I think the cleanup from other PRs and the version numbering from #107 are enough to cover this one for v0.2, we can deal with it again if/when we need to make breaking changes in a future version. I hope those will be few and far between.
