### ISSUE TITLE
socks:// proxied peerings should support SOCKS5 proxy authentication

### ISSUE THREAD

**Issue by akklesed** [yggdrasil-network/yggdrasil-go#423]
Currently auth portion of socks:// url is ignored, and proxy.SOCKS5() is always passed nil for auth argument.
Would be good idea to use it, to allow tor' `IsolateSOCKSAuth`, and also for its original purpose - authentication, in case someone actually uses this with real SOCKS5 servers.
A bit of discussion in https://github.com/yggdrasil-network/public-peers/issues/73

**Comment by Mikaela** [comment]
> I think yggdrasil using its own identity isn't bad idea, though.

Do I understand correctly that in your opinion the username (and/or password) should default to `yggdrasil` or similar if not otherwise specified so Yggdrasil connections got isolated, even if Tor was ran without `IsolateDestAddr`? Or should this be done directly in the peer list?

Typing this I started wondering how does I2P/I2Pd handle SOCKS5 proxy authentication.

**Comment by akklesed** [comment]
Ehh, I don't wanna have yggdrasil sending default username, unless we'd have something like `tor://` url for that.
That would possibly interact in bad way with actual proxies if someone use them, and also at the moment I don't really know how i2p would handle that either.
