### ISSUE TITLE
Consider using the XDG specification

### ISSUE THREAD

**Issue by yangm97** [yggdrasil-network/yggdrasil-go#465]
Pros:
- Makes docker users lives easier

Cons:
- Need to be implemented in a non-breaking way, possibly not following the whole specification

Resources: 
https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html
https://0x46.net/thoughts/2019/02/01/dotfile-madness/
https://github.com/OpenPeeDeeP/xdg

**Comment by lhanson** [comment]
+1 for the OpenPeeDeeP package. Dead simple to locate standard-compliant directories and fall back to legacy locations if they already exist.

**Comment by cathugger** [comment]
>`/etc/xdg`

am I only one totally not seeing point of this?
whole `/etc` folder is designated for configs, and thus has sorta equivalent standing as `~/.config`, no?

**Comment by lhanson** [comment]
I presume you're referring to the part of the spec that says
> If $XDG_CONFIG_DIRS is either not set or empty, a value equal to /etc/xdg should be used.

Yeah, I don't quite get the rationale for that either.

**Comment by yangm97** [comment]
> Yeah, I don't quite get the rationale for that either.

To be honest, me neither.

> possibly not following the whole specification

Think we could skip that or leave /etc/xdg as a last resort path or something which is not 1:1 to the spec but would work better for us.

**Comment by cathugger** [comment]
What other environment variable would yggdrasil use if not `$XDG_CONFIG_DIRS`?
AFAIK it currently doesn't log to any central file (except for syslog output), and is system-wide so per-user home directories wouldn't really make sense.
In fact it doesn't even centralize around `/etc/yggdrasil.conf` either, config file path is always passed as argument.
I personally find current stuff to be very comfortable, "no surprises" design, and wouldn't want that to be changed to randomly silently depend on some environment variables inside yggdrasil binary itself (unless we'd pass it argument to do so).
Start scripts (like systemd unit files) could use environment variables just fine though.

I'm honestly not really sure what would need to be changed to address this issue, does anyone have some concrete proposals, like changing systemd unit file to use `"${XDG_CONFIG_DIRS:-/etc}/yggdrasil.conf"` (that probably wouldn't work because `XDG_CONFIG_DIRS` is separated with `:`s but some idea like that)?

Or, is there issue with how currently yggdrasil binary's `-useconffile` argument specifies stuff and we'd want something like `-usexdgconf` argument to tell us to read from `${XDG_CONFIG_DIRS:-/etc/xdg}/yggdrasil.conf` (again, wouldn't work directly but one can get idea)?

What about any of above would make docker users lives easier?
Not to sound dismissive, just throwing random questions and ideas to get better understanding what could be done about this.

**Comment by yangm97** [comment]
I don't see how implementing this could cause any surprise. CLI flags always take precedence over env vars, so the current way of running it wouldn't break, nor would we need to add yet another flag. 

So the config loading would go somewhat like this:

1. kick up defaults from the codebase
2. override defaults from env vars (if any)
3. override the previous values from the CLI flags

Essentially, this should allow running passing no flags at all, but you're not forced to do so. It would try to write the config file based on the XDG rules and die if it can't (i.e. read-only filesystem), so it shouldn't pull an `-autoconf` on its own.

**Comment by neilalexander** [comment]
Is XDG a Linux-specific thing?

**Comment by lhanson** [comment]
> Is XDG a Linux-specific thing?

I would say sort of, but not exclusively. I think it fills a glaring hole in Unix-like systems while other modern operating systems seem to have stronger conventions which serve the same role. But with thoughtful implementation on non-*nix systems (mostly in terms of what defaults to use if XDG environment variables aren't set), supporting the standard is a huge win across platforms . For example, here's what the (excellent) https://github.com/OpenPeeDeeP/xdg package uses for defaults:

|  | Linux(and BSD) | Mac | Windows |
| ---: | :---: | :---: | :---: |
| `XDG_DATA_DIRS` | [`/usr/local/share`, `/usr/share`] | [`/Library/Application Support`] | `%PROGRAMDATA%` |
| `XDG_DATA_HOME` | `~/.local/share` | `~/Library/Application Support` | `%APPDATA%` |
| `XDG_CONFIG_DIRS` | [`/etc/xdg`] | [`/Library/Application Support`] | `%PROGRAMDATA%` |
| `XDG_CONFIG_HOME` | `~/.config` | `~/Library/Application Support` | `%APPDATA%` |
| `XDG_CACHE_HOME` | `~/.cache` | `~/Library/Caches` | `%LOCALAPPDATA%` |

As a developer, using that implementation means that I never have to think about where to put files again, and it Just Works on whatever environment the user has.

As a user, I know compliant programs will Just Work no matter what system I happen to be running them on, and I don't have to add special case logic for managing files between them.

**Comment by zhoreeq** [comment]
Looks like XDG is a standard for desktop applications, why would you need it for a network daemon?

**Comment by lhanson** [comment]
I don't think there's anything particular to "desktop" applications in the standard. Whether or not a program has a GUI doesn't really factor into whether it should respect a user's preferences when it's writing files to their disk.

**Comment by zhoreeq** [comment]
In case of a system daemon, OS developer decides where to store files, not a user.

**Comment by lhanson** [comment]
What do you mean, exactly, by "system daemon", and "OS developer"? These are arbitrary and irrelevant distinctions.

If you write a program that writes files to the user's disk, you have to decide where you put those files whether you're Linus Torvalds adding kernel features or some guy writing a minesweeper clone. Nobody can write files to the user's disk without deciding where they go, but instead of hard-coding some arbitrary path based on your personal fancy or interpretation of historical inertia, why not respect the user's explicit wishes if they choose to express them? You can always fall back to your personal preferences as a developer if the user doesn't care. And as a developer, why wouldn't you want your personal preferences to align with some sort of codified standard rather than your own whims?

**Comment by zhoreeq** [comment]
Existing Debian and OpenWrt packages are integrated perfectly into OS. You don't want to break it, right?

**Comment by lhanson** [comment]
As far as I know there isn't a requirement in either the Debian or OpenWrt repositories that your files be written to any particular directory. I'm pretty sure I can author a package for OpenWrt that writes its configuration to `/cool-app/configz` and its runtime files to `/.lulz/tmp/`. Does that mean every package I can possibly install is integrated perfectly into the OS?

At this point it seems likely to me that you misunderstand my position, so let me ask you: in what way would respecting the XDG specification break Debian or OpenWrt packages?

**Comment by zhoreeq** [comment]
So you REALLY want to force developers of a network daemon to comply with GNOME specs.  OK. I'll just watch.

**Comment by neilalexander** [comment]
My preference is that this is something that should be handled at a package level and not in Yggdrasil itself. 

Yggdrasil makes no assumptions about the locations of any files—all paths are provided either in the config or in the command line arguments.
