### ISSUE TITLE
Crash while configuring MTU

### ISSUE THREAD

**Issue by Vort** [yggdrasil-network/yggdrasil-go#471]
From time to time this error pops out while starting:
```
panic: Can't configure MTU as TAP adapter is not present

goroutine 1 [running]:
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).setup(0xc0000
95c50, 0xc0000127a0, 0xa, 0x1, 0xc0000df710, 0x28, 0xffff, 0x7dd9afb638da113a, 0
x6a77c23348bd90cd)
        /home/circleci/project/src/tuntap/tun_windows.go:63 +0xc9e
github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*TunAdapter).Start(0xc0000
95c50, 0xc000006238, 0x0)
        /home/circleci/project/src/tuntap/tun.go:140 +0x3fc
main.main()
        /home/circleci/project/cmd/yggdrasil/main.go:224 +0xfc2
```
Not sure if it's a latest regression or not.

Tested version: `0.3.5-0190`

**Comment by neilalexander** [comment]
I think we need a more reliable method for clearing the existing stored IP addresses on the adapter rather than disabling/enabling it, as I guess there are times where re-enabling the adapter doesn't happen fast enough before we try to configure new addresses and MTUs (as `netsh` is very slow, but I am not sure what other APIs are available).

**Comment by neilalexander** [comment]
Apparently there are no documented APIs for managing adapter IPv6 addresses without using `netsh.exe` or PowerShell—it seems you can use the IPHLP API or WMI to manage IPv4 but not IPv6. 💩 

I don't really know if calling PowerShell is any better or worse than using `netsh.exe`. We might be able to use Go's `net.Interface`-style stuff to at least discover if the interface needs to be reset or not at startup. That might make things a bit more robust in cases where the config hasn't changed, even if we can't avoid `netsh.exe` altogether.

**Comment by Vort** [comment]
I see discussions about absence of API for persistent settings.
But Yggdrasil use temporary ones (`store=active`)
[`CreateUnicastIpAddressEntry`](https://docs.microsoft.com/ru-ru/windows/win32/api/netioapi/nf-netioapi-createunicastipaddressentry) may be enough to set IPv6 address.
Also it may be enough to call [`SetMTU`](https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/setmtu-method-in-class-win32-networkadapterconfiguration) from WMI for MTU configuration.

But these changes may introduce regressions, so maybe it is good to make them later.

**Comment by neilalexander** [comment]
I think for now I'm going to assign this to the v0.3.7 milestone rather than the v0.3.6 one—it looks like there is some code out there to use `CreateUnicastIpAddressEntry`, e.g. https://github.com/GoogleCloudPlatform/compute-image-windows/blob/master/GCEWindowsAgent/addresses_windows.go so we can investigate that at some point.

**Comment by Arceliar** [comment]
It's weird that the call to `netsh` would return before the TAP is ready. I suppose we could add some artificial delay to give it a (literal) second to finish doing whatever it does, or check for the tap in a loop or something, if we're going to keep using `netsh` for the moment.

**Comment by Arceliar** [comment]
#526 should hopefully mitigate this by adding some artificial delay after each `netsh` command, in case it just needed a little time for the command to fully take effect. This isn't really a fix, but hopefully it works around the issue for now. Keeping this issue open so we remember to write a better fix in the future.

**Comment by neilalexander** [comment]
Can you please test the latest `develop` build and let us know if this is resolved now?

**Comment by Vort** [comment]
Retested with `0.3.8-0136`. Startup is not perfect:
```
2019/09/25 19:59:28 Listening for TCP on: [fe80::d1b5:de1:bfbe:e7fe%TapAdapter]:14922
2019/09/25 19:59:28 Listening for TCP on: [fe80::1889:3a3e:3a37:d631%Подключение по локальной сети 2]:14924
...
2019/09/25 19:59:30 Failed to accept connection: accept tcp [fe80::d1b5:de1:bfbe:e7fe%TapAdapter]:14922: use of closed network connection
2019/09/25 19:59:30 Stopping TCP listener on: [fe80::d1b5:de1:bfbe:e7fe%TapAdapter]:14922
2019/09/25 19:59:34 Listening for TCP on: [fe80::d1b5:de1:bfbe:e7fe%TapAdapter]:14980
...
```

But exact "MTU" crash was not happening for a long time.
Do you plan to close this report? Artificial delay is not perfect solution, do proper fix will require separate report?
> Keeping this issue open so we remember to write a better fix in the future.

**Comment by Arceliar** [comment]
The `netsh` issue seems to be that the commands to set up the network interface return before the effects of the commands have finished applying. The better alternative is to `netsh` I suppose, assuming that's possible to do. I am OK with keeping this issue open as a reminder to fix that, since technically the current solution (delaying) *could* still crash, especially if startup happens right around the time when a machine suspends or hibernates.

The issue with failed TCP listeners seems to be unrelated, so that should be a separate issue I guess.

**Comment by Vort** [comment]
This problem is fixed because of switching to Wireguard. Thanks.
