### ISSUE TITLE
Add optional authentication to peering connections

### ISSUE THREAD

**Issue by neilalexander** [yggdrasil-network/yggdrasil-go#50]
Currently peering connections are not authenticated in any way - if you know the address and port number of an Yggdrasil node, you can connect to it.

It would be good to allow optional whitelisting, perhaps by allowing specific public keys or by shared passwords, for non-multicast-configured peerings.

**Comment by Arceliar** [comment]
I'm not sure if it's the *best* place to handle this, but one of the possibilities is at the UDP and TCP links. For UDP, we could ignore any key packets coming from unrecognized keys, and TCP could close the connection if it sees an unrecognized key in the initial key exchange at the start of the connection. In both places, we could make an exception if we see that the remote address is a link-local address.

I'm not quite sure how to handle it configuration-wise. If you want to add an outgoing connection, then you'd need to add both an address and a key. For outgoing connections, you could take the key from the initial key exchange, but that may be exploitable (spoofed packet includes someone else's key -> key gets whitelisted -> attacker can now peer with you, but trying to block it by associating IP with keys may open a new DoS vector).

**Comment by neilalexander** [comment]
Perhaps from a configuration perspective, there should be a `TrustedKeys` configuration option which applies to both incoming and outgoing connections but not specifically tied to IP addresses. If `TrustedKeys` is set then both non-link-local inbound and outbound connections must satisfy the list - that way it equally prevents someone trying to intercept an outgoing connection as it does someone trying to spoof an incoming connection. Not being tied to IP addresses also means that endpoints can move freely but still maintain their trust relationship. If the option is empty/not set then all connections should be allowed, which still maintains the simplicity in connecting to a public node.

**Comment by Arceliar** [comment]
That makes sense. If you want to block everyone, then you could just add one non-existent key (or your own key).

Thinking about attack vectors, there's still a catch with this approach (no worse than what we currently have, but ugly). Someone who figures out your trusted keys (by e.g. monitoring your traffic over some network) could still connect to you and claim that their key matches on of your trusted keys. Currently, this would give them a TCP/UDP connection and a peer struct. You'd never get any valid maintenance traffic from them to set up their coords, so they wouldn't appear in the switch, but they *would* still be able to flood you with traffic that you would try to route (simple-ish fix: don't forward packets coming from a node with no switch entry, requires only a minor change to `switchTable.lookup` and where it gets called from `peer.handleTraffic`), or flood you with fake peers to make you go OOM (locking keys temporarily to an IP would fix this, but open a different DoS attack vector, though that one may be less catastrophic and/or fixable in other ways).

**Comment by neilalexander** [comment]
A potential solution might be to require a box-encrypted control message to be exchanged as a part of the initial handshake *before* the peer struct even gets created, therefore it wouldn't be sufficient to just present a false key to someone - you would need to prove your ability to use it.

It also wouldn't hurt to check the switch entries when forwarding traffic as an extra layer of hardening.

**Comment by Arceliar** [comment]
Right now, the handshake is the initial key exchange, so we can't really encrypt that. I guess we would need to add an encrypted (and sequence numbered or time stamped, to prevent replays) confirmation. This is relatively easy to do with the TCP links, immediately after the key exchange and before the peer struct setup. Not sure about UDP... maybe after we set up the link connection info, but before we create the peer struct, we start sending a periodic request for the confirmation, and we don't create the peer struct until we get one.

**Comment by Arceliar** [comment]
There's a lazy short term fix...

Allow the peer structs for spoofed traffic to get created, and then delete them after a short timeout if they don't get any valid link protocol traffic (the stuff used for the spanning tree). Probably after about the same time as the switch table timeout (~6 seconds).

This should be backwards compatible with what we have now, and forwards compatible with *most* things I can think of that would secure the key exchange.

I have half a mind to use TLS as an outer layer, partly to obfuscate that it's yggdrasil traffic, but I'm not sure it's worth the performance cost (and I don't see an obvious DTLS library to use, so that could be problematic for UDP peers).

**Comment by Arceliar** [comment]
Partly addressed by #74.

I think the plan from here is to implement some backwards-incompatible changes as part of the PR for the v0.2 release:
1. Wrap the tcp/socks and udp peer connections in a message oriented `net.Conn` interface.
2. Have `tcp.go` and `udp.go` focus on the initial conn setup and internals (e.g. UDP chunks, TCP LIFO buffers), while the common parts go into a new file (`conn.go`?)
3. Introduce new packet types for peer key exchange into `wire.go`, used for all connection types, along with a common close packet (more important for UDP than TCP).
4. Secure against remaining known forms of replay attacks. I'm thinking that peer setup should exchange ephemeral keys, save the ephemeral shared key as part of the peer struct, and then use it instead of the permanent shared key for session traffic. Re-purpose the nonce field to act as a sequence number (start at a random value, one node even and the other odd, then increment by 2 each time and drop out-of-order packets, to prevent replay attacks).

We could consider adding an outer crypto layer (nacl box or TLS) to prevent packet injection by 3rd parties, but I'm not sure if it's worth the cost given the lack of obvious uses for it. The worst case scenario I can think of is that an attacker injects a packet into an existing connection, causing it to get routed and possibly killing the connection if it's TCP. I'm not sure there's a way to prevent the connection killing side, and injecting some traffic to be routed doesn't seem like such a terrible attack, since invalid traffic is dropped.
