### ISSUE TITLE
Breakage in dependencies

### ISSUE THREAD

**Issue by Luzifer** [yggdrasil-network/yggdrasil-go#503]
At the moment builds from source are broken for version tarballs v0.3.4 to v0.3.6 as of a missing dependency version.

Looks like someone removed at least three revisions from the `github.com/yggdrasil-network/water` repo.

Affects all source builds which includes the AUR builds for Archlinux.

#### v0.3.4

```
==> Extracting sources...
  -> Extracting yggdrasil-0.3.4.tar.gz with bsdtar
==> Removing existing $pkgdir/ directory...
==> Starting build()...
Building: yggdrasil
Fetching https://golang.org/x/crypto?go-get=1
[...]
go: finding golang.org/x/text v0.3.0
go: github.com/yggdrasil-network/water@v0.0.0-20180615095340-f732c88f34ae: unknown revision f732c88f34ae
go: finding github.com/songgao/packets v0.0.0-20160404182456-549a10cd4091
go: error loading module requirements
==> ERROR: A failure occurred in build().
    Aborting...
```

#### v0.3.5

```
==> Extracting sources...
  -> Extracting yggdrasil-0.3.5.tar.gz with bsdtar
==> Starting build()...
Building: yggdrasil
Fetching https://golang.org/x/sys?go-get=1
[...]
go: finding golang.org/x/crypto v0.0.0-20181203042331-505ab145d0a9
go: finding github.com/yggdrasil-network/water v0.0.0-20180615095340-f732c88f34ae
go: github.com/yggdrasil-network/water@v0.0.0-20180615095340-f732c88f34ae: unknown revision f732c88f34ae
go: error loading module requirements
==> ERROR: A failure occurred in build().
    Aborting...
```

#### v0.3.6

```
==> Extracting sources...
  -> Extracting yggdrasil-0.3.6.tar.gz with bsdtar
==> Starting build()...
Building: yggdrasil
Fetching https://golang.org/x/crypto?go-get=1
[...]
go: finding golang.org/x/tools v0.0.0-20180917221912-90fa682c2a6e
go: github.com/yggdrasil-network/water@v0.0.0-20190725123504-a16161896c34: unknown revision a16161896c34
go: error loading module requirements
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by neilalexander** [comment]
This is a rather unfortunate side effect with our fork of the `water` library. We had a fork which contained, amongst other things, Windows and BSD support.

Someone else grew impatient waiting for us to get Windows support accepted upstream so took it into their own hands, but this meant our history diverged.

We wanted to adopt the now-new history from the upstream repository, but we also wanted to maintain BSD support so that we could get BSD support merged upstream too without filling history with useless commits (since we have enough of a hard time getting changes accepted upstream as-is), but since this is not 100% complete, it hasn't gone anywhere. 

All of this has combined resulted in breakage in `master` since Go 1.11's dependency management anchors very tightly to commits which are no longer present. This is annoying and awkward but I can live with this right now because we are still in the alpha stages and breakage is to be expected sometimes.

It's our goal to abandon the `yggdrasil-network/water` fork as soon as possible, and *definitely* before we go from alpha to beta, so that this doesn't ever happen once we leave beta.

**Comment by markbirss** [comment]
Im having build issues relating to same on master OpenWRT build from source

go: github.com/yggdrasil-network/water@v0.0.0-20190725123504-a16161896c34: unknown revision a16161896c34
