### ISSUE TITLE
Compatibility with Go's net.Conn interface

### ISSUE THREAD

**Issue by Fnux** [yggdrasil-network/yggdrasil-go#576]
Hi,

As quickly discussed on #yggdrasil:matrix.org with @neilalexander earlier today.

It would be convenient to be able to use Yggdrasil's `Conn` [0] and `Listener` [1] structures as Go 'standard' `net.Conn` [2] and `net.Listener` [3] (for use as arguments to `http.Serve` [4], in my case). To do so, we need `yggdrasil.Conn.LocalAddr()` and `yggdrasil.Conn.RemoteAddr()` to return structure compatible with `net.Addr` [5]... which is almost the case since both `Network()`  and `String()` are implemented for `yggdrasil.crypto.NodeId` [6], although `NodeId` is not a struct but an array of bytes!

I am not very familiar with Go, is there a clever trick or do we have to make `NodeId` a struct (moving the array of byte as struct member)?

I will gladly make the required changes myself.

[0] https://godoc.org/github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil#Conn
[1] https://godoc.org/github.com/yggdrasil-network/yggdrasil-go/src/yggdrasil#Listener
[2] https://golang.org/pkg/net/#Conn
[3] https://golang.org/pkg/net/#Listener
[4] https://golang.org/pkg/net/http/#Serve
[5] https://golang.org/pkg/net/#Addr
[6] https://godoc.org/github.com/yggdrasil-network/yggdrasil-go/src/crypto#NodeID

**Comment by Arceliar** [comment]
I think this is just a case of us returning concrete types instead of generic interfaces like `net.Conn`, +- a few minor things (like needing to return a `net.Addr` instead of an `address.Address`, but that should be simple enough to do). I think it makes sense to do this sooner rather than later, e.g. for v0.3.11, unless that ends up being an emergency bugfix release or something.

It's also worth considering that the current `tuntap` module contains *most* of the code (tracking individual `net.Conn`s per session) that would be needed to implement `net.PacketConn`, which may be a more natural interface to use in some cases (since our semantics are to send unordered unreliable messages, much like UDP). That would involve more refactoring, so I'm not convinced that we need to do it right away, but it may be a good idea on more of a v0.4.0 timescale (I think it would be a good idea to aim for having the interfaces exposed and mostly-stable by then).

**Comment by Fnux** [comment]
I would like to directly use net.http as client and server over yggdrasil (for use in [dendrite](https://github.com/matrix-org/dendrite)), which makes this issue a blocker for me. I will try to patch `yggdrasil.Conn` this afternoon. Could you give me more details on the reuse of `tuntap` to implement `packetConn` ?

**Comment by Arceliar** [comment]
@Fnux the code in question is kind of a spaghetti mess (we refactored things recently to add the `yggdrasil.Conn` interface, but haven't done much cleanup yet). Unless this is blocking you *now* then it may be easier to wait for us to update things, if you think the `PacketConn` interface is what you really want.

Pinging @neilalexander since he did most of the refactoring and may have some ideas, and since he said he's looking at getting the `net.Conn` part working (and I wouldn't want the two of you to waste effort both reinventing the same wheel).

So basically, within our `tuntap` code we have a map of known connections. On the side that reads from the tun/tap and writes to the `yggdrasil.Conn`s, we check that the packet is OK and to an allowed destination, and then check if we have an existing connection to a node around here:
https://github.com/yggdrasil-network/yggdrasil-go/blob/v0.3.10/src/tuntap/iface.go#L227

We then either pass the packet to some code (in `src/tuntap/conn.go`) which writes the packet to the `Conn`, or `Dial`s if none exists already.

The side that reads from the `Conn` and writes to the tun/tap is a bit simpler, we just pass any packets that arrive from the Conn to the tun/tap writer, around here:
https://github.com/yggdrasil-network/yggdrasil-go/blob/v0.3.10/src/tuntap/conn.go#L114

So my line of thinking is that  we could maintain a map of `NodeID`s onto `yggdrasil.Conn`s internally in the core library, and expose that as a `net.PacketConn` interface. This is a little more complicated than it sounds, since we'd need to make sure it works despite an incomplete `NodeID` being known (e.g. multiple `NodeID`+bitmask pairs need to map onto the same underlying `yggdrasil.Conn`), or else require the full `NodeID` while adding a `Resolve` function that searches and opens the underlying `yggdrasil.Conn` to return the full `NodeID` via the `RemoteAddr` function.

Then there's a few details we'd still need to figure out, such as how it should interact with the existing `Dial` code. Things in the protocol currently limit us to 1 crypto session existing to each node, so 1 `yggdrasil.Conn`. So either the user is responsible for `Close`-ing the `Conn` when they're done, or the `PacketConn` needs to manage that internally. It may be easiest to just say "either use the `Dial` and `yggdrasil.Conn` workflow or use the `PacketConn` workflow, but not both" and leave it up to the user to not mix them, but that may make things hard for the user if they start with one model and then realize they actually need the other one.

**Comment by Arceliar** [comment]
@Fnux followup comment, I suspect that the limiting factor for `http.Serve` is going to be that http assumes reliable and ordered stream semantics, and we have unreliable unordered datagram semantics. So what we *may* really want to do is make the `PacketConn` interface work the way things currently do, and then give an alternative stream-based `yggdrasil.Conn` to use as a replacement for TCP in applications that assume stream semantics. But then we need to add retransmission, congestion control, etc. I know there are a few existing libraries that provide reliable stream transmission over UDP (quic comes to mind, also kcp), so adapting one of those to use ygg instead of UDP may be an option...

**Comment by Fnux** [comment]
What would be the difference between `yggdrasil.Conn` and `yggdrasil.PacketConn` then?

**Comment by Fnux** [comment]
Thanks for #578. https://github.com/matrix-org/coap-proxy might be do the trick in my case.

**Comment by neilalexander** [comment]
I've merged #578 into `develop`.

**Comment by Arceliar** [comment]
@Fnux something like the coap-proxy may indeed be a good option. I can't think of any technical reason why coap over UDP couldn't have the underlying connection swapped to a `yggdrasil.Conn`, it would just be a matter of patching matrix's go-coap package I believe.

**Comment by neilalexander** [comment]
Have had some confirmation from @Fnux that the interfaces are OK in `develop` at the moment, so closing this for now. Please reopen it if there are any issues that arise.
