### ISSUE TITLE
Two instances of yggdrasil on the same device

### ISSUE THREAD

**Issue by xaozai** [yggdrasil-network/yggdrasil-go#582]
I guess no one has done it yet, but I tried running two instances of Yggdrasil on the same device (wanted to run different web services on different addresses (each with its own config)).
In the configuration files I specified different names for the tun interfaces.
IfName: tun0
IfName: tun1
Both instances started normally, received addresses, and connected to public peers. They both respond to pings.
But only one of these two addresses is available through the web server (nginx).
I assume that there is some conflict.
The web server listens at the same time on an IPv4 address, on different ports, and both sites are accessible over IPv4.
Can someone try doing the same thing to confirm if there is such a problem? )

**Comment by neilalexander** [comment]
In this instance I assume the problem is not with Yggdrasil but with your routing table. I think if you have two competing device routes for `0200::/7` then your operating system will pick one or other deterministically for return traffic, which will stop a TCP session from being established on the other interface. ICMP ping probably works because it is stateless. 

You might need to run Yggdrasil processes in separate network namespaces or similar.

**Comment by xaozai** [comment]
OK. Thanks! I'm still experimenting...
