### ISSUE TITLE
addpeer is flakey

### ISSUE THREAD

**Issue by wfleurant** [yggdrasil-network/yggdrasil-go#596]
I found when calling `addpeer` multiple times (regardless if peer connects/timesout) the first attempt is fine. The 2nd repeated call results in `Admin socket returned an error: Failed to add peer` and subsequent calls to `addpeer` lock the call up entirely. Other calls continue to work as expected but `addpeer` never recovers.  

```
root@box # yctl addpeer uri=tcp://1.0.0.1:443
Added: tcp://1.0.0.1:443

root@box # yctl addpeer uri=tcp://1.0.0.1:443
Admin socket returned an error: Failed to add peer

root@box # yctl addpeer uri=tcp://74.104.164.126:1443
^C

```

**Comment by Arceliar** [comment]
Should be fixed by #606 (in `develop`). Note that some other aspects of the API aren't implemented yet, so if e.g. you `AddPeer` then `RemovePeer` you'll be unable to `AddPeer` that particular peer again. But at least nothing should deadlock now, as far as I can tell. Feel free to reopen if the problem comes back.
