### ISSUE TITLE
Invalid 'dot' command for yggdrasilctl

### ISSUE THREAD

**Issue by i0x71** [yggdrasil-network/yggdrasil-go#654]
The following page https://yggdrasil-network.github.io/admin.html describes how you can generate a network map with the following command **yggdrasilctl dot | dot -Tpng -o map.png**

However the utility returns an error complaining of the unknown command
**Admin socket returned an error: Unknown action 'dot', try 'list' for help**

To draw a map of a node’s view of the network, install Graphviz onto your system and use dot:
yggdrasilctl dot | dot -Tpng -o map.png

**Comment by Vort** [comment]
This issue is more related to documentation:
https://github.com/yggdrasil-network/yggdrasil-go/blob/master/CHANGELOG.md:
"The admin socket can no longer return a dotfile representation of the known parts of the network, this could be rebuilt by clients using information from getSwitchPeers,getDHT and getSessions"
