### ISSUE TITLE
As the number of connections grow, doesn't the root node need to forward ever more packets?

### ISSUE THREAD

**Issue by tathougies** [yggdrasil-network/yggdrasil-go#742]
I've been experimenting with yggdrasil for a distributed wireless mesh. It looks great and can solve most of what I want (except multicast). What Im not currently sure about is the network design with regards to the root node as a single point of failure.

Firstly it seems that the root node is arbitrarily chosen which would be fine if it were not for the fact that the root node has to forward disproportionately more packets than any non root node. For example if you have a distributed network with large rack servers and small embedded hosts, then it seems to me the network would suddenly slow should an embedded host suddenly became root.

Secondly, if the root goes down, then it seems that more links would be broken than if any other node went down.

Are my concerns valid? I've not tested it out in any large scale scenario to really know and am basing my predictions based on my understanding of the protocol?

As an aside, why chord for the dht rather than kademlia.

**Comment by neilalexander** [comment]
When an Yggdrasil node receives a packet, the next-hop decision is ultimately driven by which peer will take the packet closer to the destination coordinates on the tree (so long as certain rules aren't violated, i.e. we will never forward traffic back where it came from or in any direction that takes traffic further away from the destination).

The net result of this is that traffic typically takes horizontal shortcuts between nodes and doesn't necessarily follow the vertical paths of the spanning tree when such horizontal paths are available, although vertical paths following the tree obviously remain available as a last resort.

While the root node might appear in many paths that follow the tree precisely, the ability to take shortcuts means that in reality the root node isn't terribly likely to be inundated with traffic as the network grows unless the real topology of the network actually forces such a path. Peerings between nodes further down the tree will help to alleviate this by providing shortcuts.

If the root goes down then the network will reconfigure itself around a new root, updating node coordinates in the process. At the moment this can be a bit of a destructive operation for some traffic flows but there are efforts taking place at the moment to improve that.

**Comment by neilalexander** [comment]
Oh, as for Chord vs Kademlia, older versions of Yggdrasil did use Kad but it resulted in quite a lot of idle maintenance traffic. Chord requires far less maintenance traffic and didn't appear to reduce convergence.

**Comment by Arceliar** [comment]
To elaborate on the DHT part, in Kademlia, you need at least 1 node per k-bucket to *guarantee* that you'll never run into a DHT black-hole, which means a minimum of O(logn) state is needed to guarantee that the DHT functions properly. Chord only requires O(1) state for lookups to succeed, but they'd be inefficient with O(n) lookup steps, so it needs the same O(logn) state to get O(logn) lookups steps. That turns out to be a world of difference in a lossy environment: With Kad, if someone's DHT is incomplete, then lookups fail. With Chord, if someone's DHT is incomplete, then lookups take an extra network hop to complete.

More generally, Chord lets us be more flexible about which nodes we bother to keep track of. So it's enough to *probabilistically* make sure we have enough state to have O(logn) lookup steps instead of O(n) lookup steps, since being wrong just skews the results by a constant factor, instead of breaking the whole network. And some things about Chord make it easier to prevent the DHT from diverging if/when we change the implementation (simply adding your peers to a DHT is not enough to bootstrap successfully, and there are known fixes for this problem with Chord, but I've not found any equivalent work for Kad).

**Comment by tathougies** [comment]
I understand the route can take horizontal hops but my question was.... As the network grows the chance that any two coordinates have a common ancestor that's not root gets smaller, right?

**Comment by neilalexander** [comment]
Well, that depends on a variety of factors—the peerings that the root node has, how any descendents of the root interconnect and other horizontal peerings elsewhere in the network, and whether or not the path that follows the tree is really the most optimal path at each hop.

There isn’t really any specific property of the Yggdrasil design that burdens the root specifically as the network grows, but the real answer is that “it depends” on the real network topology.

**Comment by tathougies** [comment]
I guess my question is whether around there is any proof (probabilist or not) of how likely a node is to be involved in hops given its number of descendants. I think there is not but empirical data suggests good performance. Is that correct?

Has yggdrasil been used widely for mesh wireless networking?

**Comment by Arceliar** [comment]
There's no formal proof setting bounds on how likely a node is to be involved in any given path, though the worst case would be "as often as in a spanning tree", so there may be some bounds on that (I haven't looked). It would definitely be topology dependent -- the root is *never* involved in *any* path (except for paths to the root itself) if all of the root's peers were also peered with each other, just as an example (every path would find a shortcut that bypasses the root). So I don't know if it's possible to give a general answer that applies to all possible networks.

I have a hand-wavey answer that applies to the kind of networks I think are worth worrying about. It's been empirically shown that shortest path routing does not lead to congestion for scale-free graphs (internet-like networks). Scale free graphs, or something close enough that I think the no-congestion results would still apply, tend to be the only kind of graph that ever grows large outside of a planned environment. I would argue that we don't need to care about scaling on small networks (e.g. ethernet already routes on a spanning tree, and that's good enough for most LANs, since they tend to be relatively small).

We've observed in simulation that Yggdrasil has a stretch of around ~1.01 to 1.04 on scale-free graphs (depending on which slight variation we use when constructing the tree, at least on the "skitter" network map from caida.org, which is used as a benchmark in some academic [papers](https://arxiv.org/abs/0708.2309)). That means the average path length is only about ~2% longer than if we always used the shortest path -- we almost always find the shortest path in the skitter network, and the exceptions are usually just 1 extra network hop. I don't have any reason to think it's particularly likely, but it's *possible* that the extra overhead from stretch being >1 could be biased so heavily on a few nodes that it overloads them and kills the network -- we honestly don't know.

I don't know of anyone using Ygg in any serious wireless mesh network. Most of the users I'm aware of are using it over wired connections (most often as an overlay on top of the internet). The good people over at [tomesh](https://github.com/tomeshnet) have run some wireless mesh network tests, but I can't seem to find the results that included Ygg at the moment. I don't believe it would do particularly well in a wireless mesh setting compared to the algorithms that were designed for that environment -- B.A.T.M.A.N. and Babel are probably better options, or possibly 802.11s "mesh point" wifi. I think Ygg would probably work better as an overlay on top of one of those (so they can deal with all the complexity of multi-hop wireless networking out to a few hops at least, while Ygg tries to deal with the large scale network --but this is just speculation on my part).

**Comment by neilalexander** [comment]
Closing since I think the question has been sufficiently answered. Please reopen if not.
