### ISSUE TITLE
Configurable TCP congestion control algorithm

### ISSUE THREAD

**Issue by pfactum** [yggdrasil-network/yggdrasil-go#754]
Currently, BBR is a hard-coded choice, but given there's [BBRv2 coming](https://github.com/google/bbr/commits/v2alpha) it would be nice to have a possibility to choose. FWIW, it is already available in the Liquorix and pf-kernel Linux forks.

What's suggested is having a knob in the config file for the user to choose the congestion control algorithm and not limiting Yggdrasil to BBR only.

**Comment by ShadowJonathan** [comment]
Wouldn't different congestion algorithms start to clash with eachother and produce weird behaviour?

**Comment by pfactum** [comment]
FWIW, I'm totally for ditching this option altogether in favour of using system-wide knob.

**Comment by link2xt** [comment]
> FWIW, I'm totally for ditching this option altogether in favour of using system-wide knob.

+1 on this, tweaking TCP congestion control is usually a bad idea, does more harm than good when users follow the advice of "TCP congestion control comparison" articles and select some weird experimental congestion control algorithm like YeAH TCP that are just overly aggressive and win "benchmarks" because of that. Just stick to the default (CUBIC for now) and switch to BBR/BBRv2 when/if it becomes Linux default.

**Comment by neilalexander** [comment]
v0.5 will no longer request BBR. We will leave the TCP congestion control algorithm up to the host.
