### ISSUE TITLE
Question: why is yggdrasil contrib?

### ISSUE THREAD

**Issue by Dev380** [yggdrasil-network/yggdrasil-go#763]
Hey, I was just playing around in the terminal and decided to run vrms for fun, and I noticed that yggdrasil is a contrib package on Debian/Ubuntu, why is that the case? I thought contrib was for software made to run proprietary software, so does yggdrasil run any proprietary software or is it just a misclassification? Thanks for answering.

**Comment by Arceliar** [comment]
Yggdrasil isn't proprietary, but I think that's not what `contrib` means. We don't manage the debian package, so I'm not sure what the process is for selecting where a package should end up, but based on the [policy documentation](https://www.debian.org/doc/debian-policy/ch-archive#s-contrib) I think `contrib` is correct:

>The contrib archive area contains supplemental packages intended to work with the Debian distribution, but which require software outside of the distribution to either build or function.

So packages in `contrib` are often free software (that's the case for Yggdrasil), but they're not part of the `main` debian distribution due to unusual runtime or *build* requirements. In the case of Yggdrasil, I'm guessing that the version of Go found in debian's `main` package archive is too old to build our code, so we're placed under `contrib` instead.
