### ISSUE TITLE
Problems with upgrading from 0.3.15-0091 to 0.3.15-0094

### ISSUE THREAD

**Issue by Vort** [yggdrasil-network/yggdrasil-go#767]
Looks like it is not so easy to make WinTUN-related upgrade.
First start as a service for 0.3.15-0094 results in such message:
`2021/03/12 07:39:48 An error occurred starting TUN/TAP: Error creating interface: winapi error #3758096962`
Then if I start it with admin rights as non-service, this error appears:
`2021/03/12 07:40:30 An error occurred starting TUN/TAP: The handle is invalid.`
Only at 3rd launch, when driver installation prompt appears (_not sure about it, maybe it appears at 2nd launch_), WinTUN upgrade starts:
```
2021/03/12 07:40:46 [Wintun] CreateAdapter: Creating adapter
2021/03/12 07:40:46 [Wintun] SelectDriver: Installing driver 0.10
2021/03/12 07:40:46 [Wintun] InstallCertificate: Trusting code signing certificate
2021/03/12 07:40:46 [Wintun] SelectDriver: Extracting driver
2021/03/12 07:40:46 [Wintun] SelectDriver: Installing driver
```
I think upgrade process should be tested more and corresponding manuals for users should be created.

**Comment by neilalexander** [comment]
So this is likely related to the fact that previous versions of Wintun were distributed as MSMs whereas now they are distributed as DLLs. We have had to update the installers to match.

Automated testing of this is rather difficult. I did do some manual testing of the build on a couple of virtual machines and they installed fine, but ultimately we rely on Windows users to let us know when something goes wrong. 

Not sure if there's anything we can do here or if this is ultimately a Wintun problem, since the driver is supposed to be self-installing.

**Comment by Vort** [comment]
We may wait until someone confirm such problems.
However, lots of specific may exist here: my configuration may be non-standrad in many ways.
For example, I use Win 7, when many users prefer Linux or Win 10.

**Comment by artemmolotov** [comment]
Hi, @Vort  and @neilalexander.

> 2021/03/12 07:39:48 An error occurred starting TUN/TAP: Error creating interface: winapi error #3758096962

I tried to search for the `3758096962` constant in the Google and [found error](https://win32errors.com/0xe0000242) `ERROR_AUTHENTICODE_TRUST_NOT_ESTABLISHED`. After that, I was able to quickly find [a commit](https://github.com/WireGuard/wireguard-windows/commit/b63957dc830e39c94844d2f0d32ba29575991e44) and a fix:
>Use of WireGuard on Windows 7 requires KB2921916

After installing the KB2921916 ([x64](https://download.wireguard.com/windows-toolchain/distfiles/Windows6.1-KB2921916-x64.msu), [x86](https://download.wireguard.com/windows-toolchain/distfiles/Windows6.1-KB2921916-x86.msu)), the problem was completely resolved.

**Comment by vikulin** [comment]
@neilalexander , the issue can be closed.

**Comment by neilalexander** [comment]
A note has been added to the top of the https://yggdrasil-network.github.io/installation-windows.html page about this. Thanks for finding the fix.
