### ISSUE TITLE
arm64 darwin

### ISSUE THREAD

**Issue by pkpowell** [yggdrasil-network/yggdrasil-go#793]
When executing `./build` on an apple m1 I get an x86_64 executable (which works fine under emulation). 
`env GOOS=darwin GOARCH=arm64 ./build` on the other hand errors with

```
Building: yggdrasil
github.com/yggdrasil-network/yggdrasil-go/src/multicast
# github.com/yggdrasil-network/yggdrasil-go/src/multicast
src/multicast/multicast.go:91:13: m.multicastReuse undefined (type *Multicast has no field or method multicastReuse)
src/multicast/multicast.go:104:14: m._multicastStarted undefined (type *Multicast has no field or method _multicastStarted)
```
Is it possible to build a native binary for the apple m1?

**Comment by neilalexander** [comment]
If you get an amd64 executable when running `./build` without any environment variables, it sounds like you installed Go for amd64 instead of arm64. Running `go env GOARCH` should confirm this. 

It's probably just a simple build tag thing in the multicast package which we can fix, but curious if the same thing happens if you install Go for arm64 and run `./build`?

**Comment by pkpowell** [comment]
You're right, I was on the x86_64 version. yggdrasil builds fine now.
I guess I was confused because I can build other apps (gdu, gitea etc) on the m1 by setting the appropriate env flags and always get an arm64 binary.

Thanks for the quick answer!
