### ISSUE TITLE
Question about IP addresses mining in v0.4

### ISSUE THREAD

**Issue by Vort** [yggdrasil-network/yggdrasil-go#795]
Since v0.3->v0.4 upgrade changed how IP addresses are mined, it was interesting for me to understand what maximum speed of mining can be achieved with new version.
In v0.3 secret keys were randomly generated, then scalar multiplication, edwards to montgomery conversion and SHA512 hash calculation performed.
It was possible to simplify address generation algorithm because of partial calculation of scalar multiplication for slightly different secret keys (which did not made random less secure, since only one key from block of slightly changed keys was actually used).
In v0.4 slight variation of secret keys gives nothing, since now SHA512 happens at first step, before multiplication.
The question is: can anyone throw away SHA512 step and use hash of secret key instead? Secret key is secret, so no one theoretically should know it. And since SHA512 is not reversible, no one can check if it is actually hash or just random bytes. Such change may allow to increase IP address generation speed at the cost of modifying Yggdrasil source code.
But I don't know Yggdrasil code and cryptography theory enough to understand if such scenario is possible or Yggdrasil algorithms have some protection from such hack.
_(I was looking at this problem about month ago, so I may describe some details incorrectly. Also my idea may be completely dumb. Sorry for that)_

**Comment by Arceliar** [comment]
Yes, in principle there could be a large (constant time) speedup to key generation. Instead of storing the pre-hashed seed as the private key, you could use the post-hash scalar (and adjust all of the ygg code accordingly, including a switch to a cryptographic library that lets you sign with the post-hash key).

I believe the key generation would be as simple as starting with a random scalar (as a private key) and that scalar times the base point (as a public key), and repeatedly adding a scalar 1 to the private key and the base point to the public key, and checking if the result is better than the previous best public key.

**Comment by Vort** [comment]
Thanks for the answer.
