### ISSUE TITLE
Low memory options (openwrt)

### ISSUE THREAD

**Issue by systemcrash** [yggdrasil-network/yggdrasil-go#833]
Can this monster executable be trimmed down somewhat for low memory platforms? 

I just installed on my openwrt router and it crushed all running processes with its 654meg memory demand at startup... 

Reuse memory where possible, as opposed to GC. I understand that when dealing with crypto primitives, we cycle through new memory, but surely a diet option is possible.

**Comment by yangm97** [comment]
Not sure if this info is of use but...

I remember I had issues with 0.3.16 when trying to cap the memory usage from systemd (`MemoryHigh=32M`). Yggdrasil would launch almost fine but the tun interface wouldn't get an ip assigned (`An error occurred starting TUN/TAP: message too long`) and memory usage would not drop bellow 31MB, while it would sit at ~10MB when running uncapped. I've been using `MemoryHigh=64M` since then.

The platform rocks 512MB RAM (with zram set to use 100%) and a cortex-a7 (armv7) cpu. The build was made using Yocto Project (dunfell), which uses golang 1.14.x and adds some optimizations automatically such as stripping binaries.

**Comment by neilalexander** [comment]
Closing as stale.
