### ISSUE TITLE
generate new identity / key pair / ipv6 address per request or per site

### ISSUE THREAD

**Issue by boogerlad** [yggdrasil-network/yggdrasil-go#892]
As I understand it, yggdrasil in auto mode will generate a key pair on startup that will be used for the duration yggdarsil is active. With a configuration file, it'll use that key pair as long as the configuration file is unchanged.

When visiting a site, since the site's operator can log ip addresses, the site's operator can know the time of visits and the frequency without cookies with higher accuracy than clearnet since in clearnet, ip addresses are rarely static, hidden behind NAT, and change when moving to a different network(not bound to device). This gets worse if the operator has multiple sites, since now they know the usage patterns of the user even more.

| scope  | use case |
| ------------- | ------------- |
| one key pair for everything(current)  | "this is boogerlad" across several services like github, hacker news, gmail, etc OR hosting a service |
| per site  | can eliminate login systems entirely like above, but for where a user would not like to be associated across services. for example, I'd like a pornhub account, but it should not be associated to my github account  |
| per request  | total anonymity, which I know is a non goal, but would be easy (? maybe there are performance implications...)  |

the "one key pair for everything(current)" doesn't seem to be useful. I think a sane default would be a new key pair per request, and then have the option for a user to create a one to many mapping of key pair : list of sites
```
"F3C15A...": ["github.com", "news.ycombinator.com", "gmail.com"]
"DEADBEEF...": ["pornhub.com"]
```
I know yggdrasil doesn't support dns. just making the example easier.

Please close this and correct my understanding if it's wrong.

**Comment by xlmnxp** [comment]
I hope they not do it :(
I think yggdrasil goal not to be other Tor or I2P overlay network and not to be anonymous foucs 

I think yggdrasil goal to bring the internet back to us, to host our services and have static ips not more then that

**Comment by xlmnxp** [comment]
your idea hard to do and you will need to use custom DNS and deploy multi yggdrasil nodes
then change the websites ip to custom specific one route to custom yggdrasil node

**Comment by boogerlad** [comment]
you still have the option to have a static ip address for hosting with what I'm proposing

**Comment by xlmnxp** [comment]
> you still have the option to have a static ip address for hosting with what I'm proposing
> 
> service hosts should definitely be static, but users of those services deserve some anonymity imo

You are trying to reinvent Tor

**Comment by Arceliar** [comment]
There's a few reasons why this won't or can't happen:

1. Most importantly, this is an experimental research project to develop a scalable routing scheme. Anonymity is out of scope for the project, and trying to support it would take away my already limited development time. Anonymity *may* be on the agenda for further studies after v1.0, but that's not likely to happen within the next decade or so.
2. Generating new keys would *not* hide your identity, since keys need to be mapped to coordinates in treespace for the network to find routes. So anyone who runs multiple sites would trivially see that you're the same node. If you spoofed coords in treespace, they wouldn't work unless they still contain your real coords as a prefix, so even in the best case, people would still know that all this traffic is routing *through* the same node.
3. We *cannot* completely remove treespace coordinate information and have the network continue to find routes, under the current design, and there is no interest in exploring other designs in this project (it would make sense to just start another project). If we removed it in all the places where it's technically possible, then the network still wouldn't be anonymous (*most* nodes who know any of your IDs for the DHT structure would know asymptotically close to all of them). Removing treespace information from the places where it's technically possible to do so would also *massively* increase the stretch of the routing scheme, to the extent that there's no point in even using it (other designs will find better routes for less resource cost).
4. Generating new keys per request would add a *lot* of extra strain on the network, since they need to be added to the DHT for return traffic to be routable. This doesn't just add information to the DHT, it also disrupts the DHT structure, akin to having an extremely high churn rate (proportional to the rate that new request keys are generated or expire). This would degrade network performance for all traffic through the network, even for nodes who don't want or need anonymity.

Some version of this idea is proposed every few months. There are good reasons to want anonymity, but this isn't the right project for it.

**Comment by boogerlad** [comment]
I really appreciate you for taking the time to explain this to me. Thanks! I did some searching before posting and could not find something similar. Perhaps this should be added to the FAQ?
