### ISSUE TITLE
Add PROXY Protocol

### ISSUE THREAD

**Issue by PufferBlue** [yggdrasil-network/yggdrasil-go#970]
Hello, can we add [PROXY protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt) support for listening?

I'm currently hosting https, xmpp, yggdrasil node on a single 443 port, and use Nginx for traffic dispatching.
It works but since it's proxied, I can't see the real user IPs from yggdrasil side.
If yggdrasil supports the PROXY protocol, it will get the real IP from front proxy softwares like [Nginx](https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/) and HAproxy.
And it will make peer management in such situation much easier.

**Comment by perguth** [comment]
> ... I can't see the real user IPs from yggdrasil side.
> .. it will make peer management in such situation much easier.

See where? Could you explain a bit more how you use it?

**Comment by neilalexander** [comment]
I closed the PR for this as I don't think we want to maintain support for this edge-case.

**Comment by temtemy** [comment]
I wonder if this can be reconsidered. I've been running an https + yggdrasil in port 443 for a long time, and I just recently decided to add `proxy_protocol` to my nginx since one of my https reverse proxies needed to forward the real IP to its upstream. I had to patch Yggdrasil myself based on CyberPuffer's PR which was a bit tricky since that one was pre-0.5.x, but I got it working (though it was kind of a hack since I had to make the TLS listener always use `PROXY` instead of it being an option like in the PR). You can test with openssl's `s_client` against `mima.localghost.org` and compare between no ALPN (which will route to the Yggdrasil) and with an `http/1.1` ALPN (which will route to the web server)

**Comment by tribals** [comment]
> I've been running an https + yggdrasil in port 443 for a long time...

@temtemy Could you please elaborate a little more on this? I'm planning to do the same, but wonder how it could be possible?

I've ended up with HAProxy, which could do routing based on ALPN in `tcp` mode. But I also planning to use HAProxy as "only one service who binds to 80 and 443", meaning that it should do TLS termination for all hosted Web-sites.
